### ISSUE TITLE
Add delimiters option

### ISSUE THREAD

**Issue by lpsinger** [i-like-robots/react-tag-autocomplete#12]
The old project had a `delimiters` option to control what keys (other than return) cause a new tag. How can I get this effect with the new project?

**Comment by i-like-robots** [comment]
I had no intention of implementing this feature in v7 as I have never used it myself and I've never found a reasonable spec or example to follow from the ARIA specs. What is your use case for this feature?

**Comment by lpsinger** [comment]
There are many contexts where the user would expect a comma to delimit tags, such as entering multiple email addresses.

In cases where the tags are all words without whitespace, the user would expect spaces to delimit tags.

**Comment by i-like-robots** [comment]
OK I understand.

I'm actually not sure how to make comma and space delimiters work in a consistent and intuitive way because the component now behaves a little differently to the older version. For example, in this version the only way to create a custom tag (when the `allowNew` option is enabled) is to select the create new option - hitting the enter key alone will no longer suffice. It's been changed to work this way because this is what I needed for a project and conveniently it was also easier to ensure the component works well with assistive tech.

In the use case you describe, I can see that entering an email address then pressing the comma key makes sense and this would still work as expected so long as the email address entered is in the options list. However, if the email entered isn't an option then this version of the component wouldn't do anything unless the "create new" option was also selected. Does this make sense?

**Comment by lpsinger** [comment]
It does, but this was just an example. In my use case, tags do not need to be created dynamically, but the tags are all single words, so the most intuitive delimiter would be a space.

**Comment by i-like-robots** [comment]
I'm slightly worried this could open up a can of worms (it has in the past) but it's straightforward enough to implement:

https://github.com/i-like-robots/react-tag-autocomplete/compare/allow-custom-delimiter-keys

What do you think to this?

**Comment by lpsinger** [comment]
Looks good. Thanks!
