### ISSUE TITLE
Inconsistent behavior with `onShouldExpand` and `onShouldCollapse`

### ISSUE THREAD

**Issue by acelaya** [i-like-robots/react-tag-autocomplete#49]
I'm trying to make the suggestions dropdown to not be displayed unless at least two characters have been input.

In order to do so, and following [the docs](https://github.com/i-like-robots/react-tag-autocomplete#onShouldExpand-optional), I have implemented the callbacks like this.

```tsx
<ReactTags
  onShouldExpand={(value) => {
    console.log('Should expand', value);
    return value.length > 1;
  }}
  onShouldCollapse={(value) => {
    console.log('Should collapse', value);
    return value.length < 2;
  }}
  // [...]
/>
```

## Expected behavior

The suggestions dropdown appears when the second character is input, and stays displayed as long as 2 or more characters remain.

As soon as the input has 1 or less characters, the suggestions dropdown is collapsed.

## Current behaviour

I haven't debugged any further than using the `console.log`s above, but the `onShouldExpand` callback is always invoked `onInput`, but with the previous value. For example, if I have just written `foo`, it gets called with `fo`.

Regarding `onShouldCollapse`, it never gets called `onInput`, but instead, it appears to be called `onChange`, so it only applies when the input looses focus (for example).

## Steps to Reproduce

Using the code snippet above, you should be able to see the `console.log`s as described in previous point.

## Example and screenshots

You can see it here in action on this recording (ignore the UI, I'm migrating from v6 and haven't tackled that yet).

[Grabación de pantalla desde 2023-08-12 13-40-19.webm](https://github.com/i-like-robots/react-tag-autocomplete/assets/2719332/6210ce49-492e-41fb-84ce-87227674ed12)

**Comment by i-like-robots** [comment]
Thank you for the detailed report and examples @acelaya 

I've had a look into this and I can confirm I see that the `onShouldExpand()` callback is being called with the previously rendered value and not the latest. This is because it's [being called synchronously](https://github.com/i-like-robots/react-tag-autocomplete/blob/main/src/hooks/useInput.ts#L33-L400) with the input value state change and this is a bug that needs to be fixed 🐛 

The `onShouldCollapse` callback is only called after actions which may collapse the listbox such as the blur event or pressing the escape key. It is not called on input and this is the intended behaviour.

To collapse the list box when the input value is below a certain length I'd use the `onInput` callback:

```jsx
      <ReactTags
        onAdd={onAdd}
        onDelete={onDelete}
        onShouldExpand={(value) => {
          return value.length > 1
        }}
        onInput={(value) => {
          if (value.length < 2) {
            api.current.listBox.collapse()
          }
        }}
        ref={api}
        selected={selected}
        suggestions={suggestions}
      />
```
