### ISSUE TITLE
OnDelete Launched when object inside a <label>

### ISSUE THREAD

**Issue by xavis** [i-like-robots/react-tag-autocomplete#60]
## Expected behaviour

When component is inside a label it should work as usual.

## Current behaviour

When component is inside a label it launched onDelete event on object addition and some weird behaviours.

## Steps to Reproduce

Steps to reproduce the problem:

1. Create a component wrapping the <ReactTags> with a <label> tag like: <><label><ReactTags /><label></> 
2. Make that component receive the selected, suggestions, onAdd, onDelete props from parent.
3. Render the whole component and enjoy the bug.

## Additional context

Maybe it's just me, I'm going to add my code below:

```
const TagPicker: FC<CustomTagPickerProps> = ({labelText, onUpdate, selectedTags, suggestions, ...rest}) => {
    const [component, setComponent] = useState<any>(null);

    return <>
        <label className={styles.Label}>{labelText}<br/>
           <ReactTags
              selected={selectedTags}
              suggestions={suggestions}
              onDelete={(i:number) => {
                  console.log("Delete");
                  const tags = selectedTags.slice(0);
                  tags.splice(i, 1);
                  onUpdate(tags);
              }}
              onAdd={(tag:Tag) => {
                  console.log("Add");
                  onUpdate([...selectedTags, tag]);
              }}
              labelText={labelText}
              allowNew={true}
              allowBackspace={false}
               />
        </label>
        </>
}
```
onUpdate method is a useState setter method from the parent while selectedTags is the useState value.

**IMPORTANT INFO**

I solve this issue by adding 

`onClick = { (e)=>{ e.preventDefault() } } `

to the label tag. But I think there should be some issue with the component.

**Comment by i-like-robots** [comment]
Thank you for your report @xavis. Rendering a complex component such as this one within a label element is not valid and this is not a use case I can support.

The HTML spec specififies that a label element may contain:

> [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2), but with no descendant [labelable elements](https://html.spec.whatwg.org/multipage/forms.html#category-label) unless it is the element's [labeled control](https://html.spec.whatwg.org/multipage/forms.html#labeled-control), and no descendant [label](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) elements

This component is built with multiple flow content elements (e.g. `div`) and multiple labeleable elements (`button`, `input`) that should not be rendered inside a label.

I believe the "weird behaviours" you're experiencing are due to the activation behaviour of label elements. What I expect you're seeing is that mouse events on your label element - hover, clicks, etc - are being fired as if the originated from the first interactive element rendered by this component. Here's an example given by the HTML spec:

> on platforms where clicking a [label](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) activates the form control, clicking the label in the following snippet could trigger the user agent to [fire a click event](https://html.spec.whatwg.org/multipage/webappapis.html#fire-a-click-event) at the [input](https://html.spec.whatwg.org/multipage/input.html#the-input-element) element, as if the element itself had been triggered by the user.

I hope this helps.

**Comment by xavis** [comment]
Yes, that is exactly what happens. But I was surprised about the launch of onDelete method.

Just wanted to warn about that behaviour, and mainly share the quick fix:

if anyone find the same issue would be to add e.stopPropagation() on label onClick event.

**Comment by i-like-robots** [comment]
> I was surprised about the launch of onDelete method

Hopefully this now makes sense after the explanation given above, the native activation behaviour of the label will target  the first labeleable child - in your case a selected tag. I'll reiterate that this is not valid HTML so the behaviour you and your users experience may not be predictable, especially because the activation behaviour of labels is left to the implementor and may vary between browsers, platforms and devices.
